### ISSUE TITLE
完整的QGG和QMM动作，不知道怎么联系仓库作者

### ISSUE THREAD

**Issue by ice-cream-headache** [flyteee-collections/qqpet#1]
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/zayan.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/zhaoshou.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/huaban.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/chifan.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/xiuxian.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/xizao.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/zayan.json
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/zhaoshou.json
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/huaban.json
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/chifan.json
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/xiuxian.json
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QGG/xizao.json

https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/zayan.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/zhaoshou.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/huaban.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/chifan.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/xiuxian.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/xizao.png
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/zayan.json
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/zhaoshou.json
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/huaban.json
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/chifan.json
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/xiuxian.json
https://ossweb-img.qq.com/images/MF/qqpet/res/atlas/ui/ani/QMM/xizao.json

**Comment by vsys999** [comment]
感谢您。目前通过修改代码可以免登录直接使用，但是由于先前版本缺少动作，点击这些动作后企鹅就会卡死
这些文件会上传到仓库
